/** Maps the friendly English market name to its Chinese name. */
export const zhNames: Record<string, string> = {
  'Chinatown Complex Market': '牛车水大厦巴刹',
  'Tekka Centre/Zhu Jiao Market': '竹脚中心',
  'Tiong Bahru Market': '中峇鲁巴刹',
  'Geylang Serai Market': '芽笼士乃巴刹',
  'Maxwell Food Centre': '麦士威熟食中心',
  'Kim Hua Market': '金华巴刹',
  'Adam Road Food Centre': '亚当路熟食中心',
  'Newton Food Centre': '纽顿熟食中心',
  '51 Old Airport Road Food Centre and Shopping Mall': '旧机场路熟食中心',
  'Golden Mile Food Centre': '黄金坊熟食中心',
  'Chomp Chomp Food Centre': '忠忠熟食中心',
  'Albert Centre': '阿尔柏中心',
  'Berseh Food Centre': '白锡熟食中心',
  'Zion Riverside Food Centre': '锡安河畔熟食中心',
  'Hong Lim Food Centre and Market': '芳林巴刹与熟食中心',
  "People's Park Food Centre": '珠江熟食中心',
  'Amoy Street Food Centre': '厦门街熟食中心',
  'Telok Ayer Food Centre': '直落亚逸熟食中心',
  'North Bridge Road Market': '桥北路巴刹',
  'ABC Brickworks Market/Food Centre': 'ABC砖厂巴刹与熟食中心',
  'Bukit Timah Market': '武吉知马巴刹',
  'Commonwealth Crescent Market': '联邦弯巴刹',
  'Tanglin Halt Market': '东陵福巴刹',
  'Holland Village Market and Food Centre': '荷兰村巴刹与熟食中心',
  'Holland Drive Market and Food Centre': '荷兰通道巴刹与熟食中心',
  'Ghim Moh Road Blk 20': '锦茂路第20座',
  'Clementi Ave 2 Market/Cooked Food Centre': '金文泰2道巴刹与熟食中心',
  'Taman Jurong Market and Food Centre': '达曼裕廊巴刹与熟食中心',
  'Boon Lay Place Market and Food Village': '文礼坊巴刹与美食村',
  'Jurong West Hawker Centre': '裕廊西小贩中心',
  'Yuhua Market and Hawker Centre': '裕华巴刹与小贩中心',
  'Yuhua Village Market and Food Centre': '裕华村巴刹与熟食中心',
  'Bukit Merah Central Food Centre': '红山中心熟食中心',
  'Alexandra Village Food Centre': '亚历山大村熟食中心',
  'Redhill Market': '红山巴刹',
  'Redhill Food Centre': '红山熟食中心',
  'Telok Blangah Food Centre': '直落布兰雅熟食中心',
  'Telok Blangah Market': '直落布兰雅巴刹',
  'Beo Crescent Market': '庙弯巴刹',
  'Pek Kio Market and Food Centre': '北桥巴刹与熟食中心',
  'Bendemeer Market and Food Centre': '明地迷亚巴刹与熟食中心',
  'Whampoa Drive Makan Place/Whampoa Food Centre': '黄埔通道熟食中心',
  'Whampoa Drive Makan Place/Whampoa Market': '黄埔巴刹',
  'Toa Payoh West Market and Food Court': '大巴窑西巴刹与熟食中心',
  'Toa Payoh Vista Market': '大巴窑景巴刹',
  'Kim Keat Palm Market and Food Centre': '金吉巴刹与熟食中心',
  'Chong Boon Market and Food Centre': '松文巴刹与熟食中心',
  'Cheng San Market and Cooked Food Centre': '静山巴刹与熟食中心',
  'Kebun Baru Market and Food Centre': '宏茂桥巴刹与熟食中心',
  'Kebun Baru Food Centre': '宏茂桥熟食中心',
  'Mayflower Market': '美华巴刹',
  'Ang Mo Kio 628 Market': '宏茂桥628巴刹',
  'Blk 724 Ang Mo Kio Market': '宏茂桥724巴刹',
  'Teck Ghee Court': '德义苑',
  'Teck Ghee Square': '德义广场',
  'Shunfu Mart': '顺福商场',
  'Serangoon Garden Market': '实龙岗花园巴刹',
  'Hougang 105 Hainanese Village Centre': '后港105海南村中心',
  'Kovan Hougang Market and Food Centre': '高文后港巴刹与熟食中心',
  'Ci Yuan Hawker Centre': '茨园小贩中心',
  'Bedok Food Centre': '勿洛熟食中心',
  'Bedok Interchange Hawker Centre': '勿洛转换站小贩中心',
  '85 Fengshan Centre': '85凤山中心',
  'Kaki Bukit 511 Market and Food Centre': '加基武吉511巴刹与熟食中心',
  'East Coast Lagoon Food Village': '东海岸美食村',
  'Dunman Food Centre': '敦曼熟食中心',
  'Marine Parade Central Blk 84': '马林百列中心第84座',
  'Changi Village Blk 2 and 3': '樟宜村第2和3座',
  'Pasir Ris Central Hawker Centre': '巴西立中心小贩中心',
  'The Hawker Centre @ Our Tampines Hub': '淡滨尼天地小贩中心',
  'Tampines Round Market and Food Centre': '淡滨尼圆巴刹与熟食中心',
  'Fernvale Hawker Centre and Market': '芬维尔小贩中心与巴刹',
  'Buangkok Hawker Centre': '万国小贩中心',
  'Senja Hawker Centre': '森雅小贩中心',
  'Bukit Panjang Hawker Centre and Market': '武吉班让小贩中心与巴刹',
  'Chong Pang Market and Food Centre': '忠邦巴刹与熟食中心',
  'Yishun Park Hawker Centre': '义顺公园小贩中心',
  'Kampung Admiralty Hawker Centre': '甘榜海军部小贩中心',
  'Marsiling Mall Hawker Centre': '马西岭商场小贩中心',
  'Woodleigh Village Hawker Centre': '兀里小贩中心',
  'One Punggol Hawker Centre': '榜鹅综合社区中心小贩中心',
  'Punggol Coast Hawker Centre': '榜鹅海岸小贩中心',
  'Anchorvale Village Hawker Centre': '安谷村小贩中心',
  'Margaret Drive Hawker Centre': '玛格烈通道小贩中心',
  'Bukit Canberra Hawker Centre': '武吉坎贝拉小贩中心',
  'Bukit Batok West Hawker Centre': '武吉巴督西小贩中心',
  'Market Street Hawker Centre': '马吉街小贩中心',
  'Kallang Estate Fresh Market and Food Centre': '加冷鲜巴刹与熟食中心',
  'Empress Road Market and Food Centre': '女皇道巴刹与熟食中心',
  'Pasir Panjang Food Centre': '巴西班让熟食中心',
  'Haig Road Market and Cooked Food Centre': '海格路巴刹与熟食中心',
  'Sims Vista Market and Food Centre': '沈氏坊巴刹与熟食中心',
  'Havelock Road Cooked Food Centre': '合洛路熟食中心',
  'Blk 117 Aljunied Market and Food Centre': '阿裕尼117巴刹与熟食中心',
  'Blk 69 Geylang Bahru Market and Food Centre': '芽笼峇鲁69巴刹与熟食中心',
  '50A Marine Terrace': '马林台50A',
  'Teban Gardens Market and Food Centre': '德坂花园巴刹与熟食中心',
  '11 Telok Blangah Crescent Market and Food Centre': '直落布兰雅弯11巴刹与熟食中心',
  'Ayer Rajah Market': '亚逸拉惹巴刹',
  'Ayer Rajah Food Centre': '亚逸拉惹熟食中心',
  'Mei Chin Road Market': '美芹路巴刹',
  'Blk 6 Tanjong Pagar Plaza Market and Food Centre': '丹戎巴葛广场巴刹与熟食中心',
  'Kukoh 21 Food Centre': '库河21熟食中心',
  'Blk 4A Jalan Batu Hawker Centre/Market': '惹兰勿刹4A小贩中心',
  'Blk 17 Upper Boon Keng Market and Food Centre': '文庆路上段17巴刹与熟食中心',
  'Blk 115 Bukit Merah View Market and Food Centre': '红山景115巴刹与熟食中心',
  'Blk 112 Jalan Bukit Merah Market and Food Centre': '惹兰红山112巴刹与熟食中心',
  '80 Circuit Road Market and Food Centre': '切路80巴刹与熟食中心',
  '84 Marine Parade Central Market and Food Centre': '马林百列中心84巴刹与熟食中心',
  'Jalan Leban Food Centre': '惹兰里万熟食中心',
  'Sembawang Hills Food Centre': '三巴旺山熟食中心',
  'Bedok North Street 1 Blk 216': '勿洛北1街第216座巴刹',
  'Bedok North Street 3 Blk 538': '勿洛北3街第538座巴刹',
  'Bedok Reservoir Road Blk 630': '勿洛水池路第630座巴刹',
  'Bedok South Road Blk 16': '勿洛南路第16座巴刹',
  'Circuit Road Blk 79/79A': '切路第79/79A座巴刹',
  'Circuit Road Blk 89': '切路第89座巴刹',
  'Clementi Ave 3 Blk 448': '金文泰3道第448座巴刹',
  'Clementi West Street 2 Blk 726': '金文泰西2街第726座巴刹',
  'Eunos Crescent Blk 4A': '友诺士弯第4A座巴刹',
  'Jurong West Street 52 Blk 505': '裕廊西52街第505座巴刹',
  'Marsiling Lane Blk 20/21': '马西岭巷第20/21座巴刹',
  'New Upper Changi Road Blk 58': '新樟宜路上段第58座巴刹',
  'Telok Blangah Rise Market': '直落布兰雅岭巴刹',
  'Toa Payoh Lorong 4 Blk 93': '大巴窑4巷第93座巴刹',
  'Toa Payoh Lorong 5 Blk 75': '大巴窑5巷第75座巴刹',
  'Toa Payoh Lorong 8 Blk 210': '大巴窑8巷第210座巴刹',
};
